version: '3.8'

services:
  ui_component_library:
    container_name: mahfuj_coding_assignment13
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8018:8018"
    restart: unless-stopped