name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run ESLint (continue on error)
      run: npm run lint || echo "Linting issues found but continuing build"
      continue-on-error: true
    
    - name: Check formatting with Prettier (continue on error)
      run: npx prettier --check "src/**/*.{js,jsx,ts,tsx,css,scss,md,json}" || echo "Formatting issues found but continuing build"
      continue-on-error: true
    
    - name: Run tests
      run: npm test -- --run
    
    - name: Build
      run: npm run build